# Generated by Django 3.1.7 on 2021-06-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_id', models.TextField(blank=True, null=True)),
                ('incipit', models.TextField(blank=True, null=True)),
                ('cantus_id', models.TextField(blank=True, null=True)),
                ('mode', models.TextField(blank=True, null=True)),
                ('finalis', models.TextField(blank=True, null=True)),
                ('differentia', models.TextField(blank=True, null=True)),
                ('siglum', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('folio', models.TextField(blank=True, null=True)),
                ('sequence', models.FloatField(blank=True, null=True)),
                ('marginalia', models.TextField(blank=True, null=True)),
                ('cao_concordances', models.FloatField(blank=True, null=True)),
                ('feast_id', models.TextField(blank=True, null=True)),
                ('genre_id', models.TextField(blank=True, null=True)),
                ('office_id', models.TextField(blank=True, null=True)),
                ('source_id', models.TextField(blank=True, null=True)),
                ('melody_id', models.TextField(blank=True, null=True)),
                ('drupal_path', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('full_text_manuscript', models.TextField(blank=True, null=True)),
                ('volpiano', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dataset_name', models.TextField(blank=True, null=True)),
                ('dataset_idx', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chant',
                'managed': False,
            },
        ),
    ]
