# Generated by Django 3.1.7 on 2022-05-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melodies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chant',
            options={'managed': True},
        ),
    ]
