# Generated by Django 3.1.7 on 2022-05-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodies', '0002_auto_20220529_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='chant',
            name='century_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
